import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import ConditionalNavbar from "../components/ConditionalNavbar";
import ConditionalFooter from "../components/ConditionalFooter";
import FloatingWhatsAppCTA from "../components/FloatingWhatsAppCTA";
import LeadCapturePopup from "../components/LeadCapturePopup";
import initializeServices from "@/lib/init";

// Initialize MongoDB and Cloudinary on app startup
initializeServices();

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","400","600","700","800"],
});

export const metadata: Metadata = {
  title: "PadhAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ConditionalNavbar />
        {children}
        <ConditionalFooter />
        <FloatingWhatsAppCTA />
        <LeadCapturePopup />
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-19CRNPTLP5"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-19CRNPTLP5');
          `}
        </Script>
      </body>
    </html>
  );
}
