import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import FloatingWhatsAppCTA from "../components/FloatingWhatsAppCTA";
import LeadCapturePopup from "../components/LeadCapturePopup";
import initializeServices from "@/lib/init";

// Initialize MongoDB and Cloudinary on app startup
initializeServices();

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","400","600","700","800"],
});

export const metadata: Metadata = {
  title: "PadhAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <FloatingWhatsAppCTA />
        <LeadCapturePopup />
      </body>
    </html>
  );
}
